### ISSUE TITLE
Marshalling a time.Time field as child in slice of struct

### ISSUE THREAD

**Issue by lvignoli** [sblinch/kdl-go#1]
As the following example shows,  when marshalling a slice of struct, a time.Time field is not marshalled as a child node despite the struct tag.

https://go.dev/play/p/23xtZb3dWDQ

Thanks for this great library! 😃

**Comment by sblinch** [comment]
Fixed by 9fa9a50, thanks!

**Comment by lvignoli** [comment]
Amazing, thank you!
