### ISSUE TITLE
Using KDL for config and unmarshal failing

### ISSUE THREAD

**Issue by cgrinds** [sblinch/kdl-go#2]
Thanks for creating kdl-go and especially investing so much effort into the docs. Appreciated! I'm trying to move a yaml struct config to kdl structs, and haven't managed to make it work yet.

I've pasted my code below.

When I run this the following is printed:
 
`{Defaults:{Name: Manager:false Shifts:12} Staff:[]}`

`Defaults` is populated with `shifts = 12` as expected, but the slice of Staff is empty. Any idea what I'm doing wrong?

```go
package main

import (
	"fmt"
	"github.com/sblinch/kdl-go"
)

func main() {
	data := `
defaults {
  shifts 12
}

team {
  staff "Olivia" manager=true
  staff "Ethan"
  staff "Ava"
  staff "Harper" shifts=10
  staff "Lucas"
  staff "Mason" manager=true
  staff "David" shifts=4
  staff "Ian" manager=true
  staff "Sophia"
  staff "Lily" manager=true
}
`

	var cfg Config

	err := kdl.Unmarshal([]byte(data), &cfg)
	if err != nil {
		panic(err)
	}

	fmt.Printf("%+v\n", cfg)
}

type Config struct {
	Defaults Staff `kdl:"defaults"`
	Staff []Staff `kdl:"team"`
}

type Staff struct {
	Name    string `kdl:"staff,multiple"`
	Manager bool  `kdl:"manager"`
	Shifts  int  `kdl:"shifts"`
}
```

**Comment by sblinch** [comment]
You have to represent the `team` block, and the `multiple` should be on `Staff []Staff`, not `Name`. Try this:

```go
	type Team struct {
		Staff []Staff `kdl:"staff,multiple"`
	}

	type Config struct {
		Defaults Staff `kdl:"defaults"`
		Team     Team  `kdl:"team"`
	}
```

**Comment by cgrinds** [comment]
Thanks. Did that work for you? When I use those structs, `Unmarshal` returns an error `staff has unexpected arguments`

**Comment by sblinch** [comment]
Sorry, I omitted the `Staff` struct:

```go
	type Staff struct {
		Name    string `kdl:",arg"`
		Manager bool   `kdl:"manager"`
		Shifts  int    `kdl:"shifts"`
	}
```

In your KDL, `Name` is an argument, not a property, so you have to tag it as such.

**Comment by cgrinds** [comment]
Thanks! That worked. Appreciate the library and the help.
